---

- hosts: workstation
  tasks:

  - name: install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.5.6/terraform_1.5.6_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root 

- hosts: web_server
  tasks:

  - name: install apache
    tags: CentOS 
    package:
      name:
        - "{{ apache_package }}"

  - name: copying default html files
    tags: httpd
    copy:
     src: default_site.html
     dest: /var/www/html/index.html
     owner: root
     group: root
     mode: 0644 
