---

- hosts: all
  pre_tasks:

  - name: update repositry index (CentOS)
    tags: always
    package:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "CentOS"

- hosts: all
  roles:
    - base

- hosts: workstation
  roles:
    - workstations

- hosts: web_servers
  roles:
    - web_servers

- hosts: file_servers
  roles:
    - file_servers


